#!/usr/bin/python
# -*- coding: utf-8 -*-

"""Usage:
  pyvpn connect
  pyvpn disconnect
"""

from docopt import docopt

from lib import connect

if __name__ == '__main__':
    arguments = docopt(__doc__, version='dev')
    if arguments['connect']:
        connect.main()
    if arguments['disconnect']:
        connect.disconnect()